# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule:
  - cron: "0 16 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          # plugin_languages: yes
          # plugin_languages_recent_days: 365
          # plugin_languages_recent_load: 1000
          # plugin_languages_analysis_timeout_repositories: 15
          # plugin_languages_analysis_timeout: 60
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
          plugin_achievements_display: compact
          plugin_notable: yes
          plugin_notable_filter: stars:>10
          plugin_notable_repositories: yes