# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule:
  - cron: "0 16 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: justmike1
          template: classic
          config_timezone: Asia/Jerusalem
          plugin_introduction: no # yes
          plugin_introduction_title: no # yes
          plugin_isocalendar: no # yes
          plugin_isocalendar_duration: full-year
          plugin_lines: no # yes
          plugin_traffic: no # yes
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_ignored: octonaut
          plugin_achievements_limit: 0
          plugin_achievements_display: compact
          plugin_notable: yes
          plugin_notable_filter: stars:>0
          plugin_notable_repositories: yes
