# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule:
  - cron: "0 16 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Revert to lowlighter/metrics@latest after https://github.com/lowlighter/metrics/issues/1706 addressed
      - uses: stalomeow/metrics@projects-v2
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
